org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

archives_base_name=matthiesen-lib-webhooks
mod_id=matthiesen_lib_webhooks
mod_version=1.x-DEV-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Matthiesen Lib Webhooks
mod_description=A Server-side library mod for Matthiesen Lib projects that want to be able to send discord webhooks easily
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/matthiesen-lib-webhooks/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/matthiesen-lib-webhooks
git_url=github.com/Matthiesen-dev/matthiesen-lib-webhooks
modrinth_url=https://modrinth.com/mod/matthiesen-lib-webhooks

# Used for prism deployment, not consumed by build-logic
minecraft_version=1.21.1